sudo: required
dist: trusty
language: python
addons:
  apt:
    packages:
    - python-gi
    - python3-gi
matrix:
  include:
    - python: "3.4"
      env: TOXENV=py3
    - python: "2.7"
      env: TOXENV=py2
virtualenv:
  system_site_packages: true
install:
  - sudo apt-get -y install gir1.2-gstreamer-1.0 gir1.2-gst-plugins-base-1.0
  - sudo apt-get -y install libgstreamer1.0-dev gstreamer1.0-plugins-good
  - sudo apt-get -y install gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly
  - sudo apt-get -y install software-properties-common
  - sudo add-apt-repository -y "deb http://us.archive.ubuntu.com/ubuntu/ trusty universe multiverse restricted"
  - sudo add-apt-repository -y "deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates universe multiverse restricted"
  - sudo apt-get -y update
  - sudo apt-get -y install ubuntu-restricted-extras
  - pip install tox coveralls
  - test/download_data.sh
script:
  - tox -e ${TOXENV}
after_success:
  - coveralls

